### ISSUE TITLE
[SUGGESTION/OPTION] Cloud hosting instead of slow raspberry pi

### ISSUE THREAD

**Issue by misslame** [misslame/BroncoderBot#38]

**Comment by GuyWhoCode** [comment]
# Setting bot up on Heroku:
## Requirements
1. Create account with [Heroku](https://www.heroku.com/)
2. Attach credit card information to your account under Account Settings => Billing (I used a prepaid visa with like $5)
- By default, Heroku gives 500 hours of service a month before shutting down. Attaching a credit card gives 1000 hours of service total, meaning that the bot won't be down due to lack of hours, provided that you don't host multiple bots at once on the same account.

3. Create a new app => Deploy => Connect to Github => Choose repo
4. Allow for automatic deploys, but when building the bot for the first time, a manual deploy is needed.
![Automatic Deploy Img](https://user-images.githubusercontent.com/34526187/175836913-c8b41fd5-5dad-4dcc-9b35-b168170f9a35.png)
5. In Settings tab, set environment variables.
![env](https://user-images.githubusercontent.com/34526187/175836949-8cedb573-35b5-400c-a730-eb681732c6f7.png)
6. [Follow instructions here to set up Selenium on Heroku](https://www.andressevilla.com/running-chromedriver-with-python-selenium-on-heroku/) 
7. In the actual repository, Heroku looks for a file named `Procfile` as a command to host. In the file, type in the following: `worker: python3 main.py`
8. [Insert something about adding headless idk]
9. Bot logs and debugging statements are under More => View Logs
![image](https://user-images.githubusercontent.com/34526187/175837303-dea274b4-a9a3-4d7d-9c61-26c6c3ef8ba3.png)


## Turning the Bot off
1. In Overview => Configure Dynos
![Config Dynos](https://user-images.githubusercontent.com/34526187/175837114-16004dc4-4e99-4b8a-a262-55788760b6ce.png)
2. Click pencil icon and then switch.
3. In Settings tab, turn on Maintenance Mode (bottom of page).
4. Finalize changes by restarting dynos. Restarting dynos is the same as restarting the bot.
![Resarting Dynos / Bot](https://user-images.githubusercontent.com/34526187/175837211-5d29351b-7f2d-4365-bda9-1de6c2a45826.png)

**Comment by GuyWhoCode** [comment]
Cloud Hosting on Heroku is currently being hindered by issues with Selenium when attempting to submit an answer. See the following comments for more information about the current progress:
https://github.com/misslame/BroncoderBot/blob/f1b14b8a0e4fd3c955d450abeb877b5473e5b0c2/submission_handling/selenium.py#L178-L180
